### ISSUE TITLE
Server Side Copy 

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#1]
### Summary: 
Users are unable to copy data within a project or bucket without downloading it and uploading it to the new location.

### Pain Point:
Copying data without server-side copy is costly because the user must pay for the download bandwidth. 

### Intended Outcome
Users will have the ability to copy data from one location to another within a project without having to download and reupload it. This will enable users to move data within their projects and buckets without having to pay for egress bandwidth. This functionality will be added to the library's and CLI tool first and then incorporated into the satellite GUI later. 

### How will it work?
The technical details of how this functionality will work can be found on the blueprint. 

### Links: 
Storj Milestone: https://github.com/storj/storj/milestone/5
Uplink Milestone: https://github.com/storj/uplink/milestone/1
Blueprint: https://review.dev.storj.io/c/storj/storj/+/5930
Test Plan: https://github.com/storj/storj/pull/4317

**Comment by jtolio** [comment]
Note from OKR tracking spreadsheet:
> Pending no design issues, there is a strong possibility this will be completed by end of Q1, but it will be tight.

**Comment by shaupt131** [comment]
## Week 11 update:

**Satellite**
- Optimization work in progress
- Adjusting deletion of bucket 

**Uplink**
- Uplink implementation is merged
- Working on overriding metadata

**Next Steps**
- Integrating with Uplink CLI binary
- Integrating with gateway

**Comment by shaupt131** [comment]
## Week 13 update: 

**Satellite:** 

- Continued optimization work
- Finalizing deletion logic
- Finalizing ancestor references and management
- Solving unexpected CRDB changes that affected functionality. 

**Uplink:**

- Determining and building test cases

**Next Steps:**

- Continue determining and building more test cases
- Working on overwriting destination on copy

**Comment by shaupt131** [comment]
## Week 15 update:

- Deployed into production, but currently behind a feature flag.
  - Will be enabled on all satellites in the next release.  
- Functionally 99% complete, including most relevant features
- Passed QA
- Gateway-ST version update ready for release

**Next Steps:**

- Product to write up a blog post
- Continue to determine and build more test cases, including testing in production
- Continue to assess what features will be added at a later date
