### ISSUE TITLE
Partner Value Attribution

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#14]
### Summary: 
As a part of our partner program, we want to incentivize the use of our network for data storage needs. For Example, an open-source project can build an integration with Storj and the incentive for that project to do so is we will do revenue sharing with them. 

### Pain Point:
Currently, our value attribution system requires us to specify partners on a [file](https://github.com/storj/storj/blob/main/satellite/rewards/partners.go) in the satellite. We want to change how this works so that we can keep track of user agents from projects that are not on that list. 

### Intended Outcome:
Partners can pass a user agent through their application to Storj and start to receive attribution for all of the data storj on Storj for them. 

### links
Milestone: https://github.com/storj/storj/milestone/7

**Comment by NiaStorj** [comment]
### **Week 17 Update:**

Current Status: 

- able to generate a report

Next Steps: 

- generate free usage for parters.  
- draft a ticket

**Comment by NiaStorj** [comment]
**### Week 23 Update:**

Final ticket for MVP should be released next week.
