### ISSUE TITLE
Manual Freeze admin API / Auto Unfreeze User Accounts

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#17]
*MVP: freeze user accounts via admin api, auto unfreeze when new payment method is added 
https://github.com/storj/storj/milestone/23

### Summary: 
Satellites don't automagically freeze user accounts. If a user does not pay their invoice or does something against the terms of use we must manually freeze their account and contact them. 

### Job Stories: 
- When a user fails to pay their invoice I want to freeze their account so that they are not able to accumulate usage until their bill is paid. 
- When a frozen user accounts bill is paid I want their account to be unfrozen instantly so that they can continue to use the service. 

### Pain Point:
- Freeze user accounts is a manual time-consuming process right now. 

### Intended Outcome:
- User accounts are frozen during certain circumstances.
- User accounts are automatically unfrozen when no longer under those circumstances. 
- Users are notified of potential account freeze before, and when it happens.
- Users are notified when their account is unfrozen. 
- Notifications must include the cause so that users understand why it was frozen and how to avoid the situation in the future.

**Comment by NiaStorj** [comment]
Ready to start technical goals.  
Needs ordered list of important items. 
   ie. what circumstances accounts should be frozen or unfrozen

**Comment by NiaStorj** [comment]
Design doc completed. 

Make Unfreeze automatic.  
Admin UI Oauth

**Comment by stoweandi** [comment]
Released in 1.70.1
