### ISSUE TITLE
Macaroon based Enforced Immutability

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#25]
### Summary:
Delegated authorization models can be used in conjunction with server-side or end-to-end encryption configurations. This approach provides significant protection against credential-based attacks because no subsequent change to account or bucket configurations can alter the authorization or access of a credential once created. Moreover, credentials are cryptographically verifiable, making it impossible to tamper with or alter the authorization restrictions encoded in the credentials.

### Pain Points:
- We don't have good documentation on how to achieve macaroon-based enforced immutability. 

### Intended Outcome:
- Technical documentation is created that explains how users can leverage this functionality.

**Comment by jggleeson** [comment]
https://docs.storj.io/dcs/immutability

**Comment by iglesiasbrandon** [comment]
Documentation is update, we are going to close this item until becomes more relevant.
