### ISSUE TITLE
Satellite Interface Enforced Immutability

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#26]
### Summary
- As an application owner, I want to add an additional layer of security to prevent credential-based attacks. I would like to be able to enforce restrictions on the creation of API Keys to ensure the immutability of data stored on the network. This includes accounting for multiple project team members with access to Access Grant creation and the creation of subsequent Access grants on a project with existing data.
 
### Pain Point
- While Access Grants can be constructed to achieve immutable data storage, users on Projects can subsequently create unrestricted credentials that can interact with any data stored on the platform. 

### Intended Outcome
- A Project Owner can restrict Access Grant creation by Project users to enforce immutability.

**Comment by jtolio** [comment]
Please see https://review.dev.storj.io/c/storj/storj/+/8968/2/docs/blueprints/bucket-policies.md

**Comment by iglesiasbrandon** [comment]
closing this issue until it becomes more relevant.
