### ISSUE TITLE
Auth Database Refactor Code-complete

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#3]
### Summary: 
We want to replace CockroachDB with something else. The new solution will be based on a key-value store like BadgerDB and use replication with relaxed consistency constraints. The auth service does not need strong consistency, so an eventually, consistent database will simply It. 

### Pain Point:
CockroachDB is too complicated to run and maintain for a simple service like this one especially because this service does not need strong consistency.

### Intended Outcome:
The auth service database will be replaced with something other than CockroachDB. This should allow us to reduce the number of requests not handled due to cross-regional latency, lower maintenance costs, make some queries less complicated due to the nature of our data model and make it easier for other people (e.g. community) to run auth service in a cluster.

### Links:
Blueprint: https://review.dev.storj.io/c/storj/gateway-mt/+/6030/33/docs/blueprints/new-auth-database.md#12
Milestone: https://github.com/storj/gateway-mt/milestone/1

**Comment by shaupt131** [comment]
## Week 11 update

**Completed**
- Implementation of data model is now merged.
- Initial implementation of key value interface is now merged.

**In Progress**
- Finishing framework for testing
- Finishing simple testing single node cluster
- Creating more complex testing scenarios
- Implementing replication algorithm
- Cleaning up issues after review of dependencies.

**Comment by shaupt131** [comment]
## Week 15 update

**Completed**

- Implemented structural changes to reduce the scope of project
- Consolidated update/insert logic

**In Progress**

- Finishing replication
- Building test cases
- Implementing backup mechanism for nodes
- Investigating new interfaces for tooling

**Comment by shaupt131** [comment]
## Week 17 update

**Completed**

- Building test cases
- Configuration of nodes for connections
- Setting up messaging between nodes

**In Progress**

- Finishing replication
- Implementing backup mechanism for nodes
- Investigating new interfaces for tooling
- Setting up test cluster

**Comment by shaupt131** [comment]
## Week 19 update

**Completed**

- Replication
- Investigation of new interfaces for tooling

**In Progress**

- Implementing backup mechanism for nodes
- Setting up test cluster
- Implementing zero-downtime migration
- Further testing 
- Coordinating with QA team on additional testing

**Comment by shaupt131** [comment]
## Week 21 update

**Completed**

- Setting up test cluster
- Coordinating with QA team on additional testing

**In Progress**

- Implementing backup mechanism for nodes
- Implementing zero-downtime migration
- Further testing 
- Documentation
- Implementing admin tool

**Comment by shaupt131** [comment]
## Week 23 update

**Completed**

- Implementing backup mechanism for nodes
- Implementing zero-downtime migration
- Documentation

**Ongoing Enhancements**

- Further testing 
- Implementing admin tool
