### ISSUE TITLE
Remaining strong consistency cleanup

### ISSUE THREAD

**Issue by jtolio** [storj/roadmap#31]
After https://github.com/storj/roadmap/issues/18 is done, we need to make sure we can declare success and market strong consistency across our product. #18 should be sufficient, but we need to confirm.

Acceptance criteria: all Uplink operations provide at least strong read-after-write consistency (https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/), but it would be better to be higher up on https://jepsen.io/consistency.

**Comment by mniewrzal** [comment]
@jt @onionjake looking at https://jepsen.io/consistency did we have in mind any specific level of consistency? or we should try to achieve highest `Strict Serializability` consistency level.

**Comment by onionjake** [comment]
@mniewrzal We don't need to provide any more guarantees than the underlying metainfo database, so CRDB's default consistency. Additionally, the guarantees for our product are only for object operations, not bucket or otherwise.

**Comment by iglesiasbrandon** [comment]
global milestone: https://github.com/storj/storj/milestone/28

**Comment by iglesiasbrandon** [comment]
closing this issue until it becomes more relevant.
