### ISSUE TITLE
Encryption Key UX | project-level passphrase

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#42]
When a customer creates a project, I want them to be able to create a passphrase that is associated with all buckets and files within that project so that they only have to enter their passphrase once per session instead of every time they open a bucket. 

AC:
- user is able to only enter a passphrase once per session to access all contents within a project
- user can switch to a different passphrase if desired within a project
- user can clear the passphrase for that session

**Comment by NiaStorj** [comment]
ROM:  3 sprints

**Comment by boshevski** [comment]
Prototype:
https://www.figma.com/proto/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=19152%3A173943&scaling=scale-down&page-id=19152%3A170135&starting-point-node-id=19152%3A173943&show-proto-sidebar=1

Figma designs:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=19152%3A170135&t=l69ffawA4i63GrwS-0

**Comment by iglesiasbrandon** [comment]
https://github.com/storj/storj/milestone/27

**Comment by stoweandi** [comment]
Released in 1.70.1
