### ISSUE TITLE
Forgotten Deletes

### ISSUE THREAD

**Issue by shaupt131** [storj/roadmap#49]
In the event of a DB restoration from backup, it may be possible for deleted segments to be restored. This would result in the satellite auditing these pieces and the nodes will fail. 

Nodes need some way to prove that pieces were legitimately deleted.

Mentioned on:
https://storjlabs.atlassian.net/wiki/spaces/NEWS/pages/925434065/Durability+2020-10-12
https://storjlabs.atlassian.net/wiki/spaces/NEWS/pages/890273817/Durability+2020-09-28
https://storjlabs.atlassian.net/wiki/spaces/ENG/pages/1716781220

[Formerly DUR-58](https://storjlabs.atlassian.net/browse/DUR-58?atlOrigin=eyJpIjoiZjNjMmU4NWNmOTg5NGYyYTg3ZDllNTYxZWUxMzYxMTIiLCJwIjoiaiJ9)

**Comment by iglesiasbrandon** [comment]
We are closing this issue until it become relevant and decide its worth the effort.
