### ISSUE TITLE
Native STORJ Token Deposits (Customer Payments)

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#5]
### Summary: 
The satellites currently use a third-party service to accept STORJ Token payments. The use of this service creates a set of problems for users and satellite operators. Removing the use of this third-party service is going to alleviate these pain points. 

### Pain Point:
It's not always advantageous for users to pay in STORJ Token because of the transaction fees charged by the third-party service we currently use. Relying on a third-party service for Token payments also makes it more difficult to stand up to community satellites. The third-party service we use generates a new wallet address for each payment made by a user, this is a problem because users do not have a consistent deposit address. We want to give our users a single stable deposit address they can reliably send tokens to that will be associated with their account. With the satellite controlling the deposit addresses, it would also make reporting on the Token payments easier for satellite operators. 

### Intended Outcome:
The satellite will generate a deposit address for a user who wants to deposit Tokens into their account. The satellite will keep track of these wallets as well as the transactions (deposits) made to them and which users they belong to.

### How will it work?
The satellite will have a service that generates wallets and monitors the Etherum blockchain for transactions to the wallets it generated. 

### Links:
BluePrint: https://storjlabs.atlassian.net/wiki/spaces/TD/pages/2310733825/Native+Token+Payments+Design
Test Plan: https://github.com/storj/storj/pull/4342
Storj Milestone: https://github.com/storj/storj/milestone/2
Storjscan Milestone: https://github.com/storj/storjscan/milestone/1

**Comment by jtolio** [comment]
Note from OKR tracking spreadsheet:
> Code should be completed by end of Q1, but QA and deployment may take longer.  Also UI work to consider.

**Comment by shaupt131** [comment]
## Week 9 update:
- Lots of boilerplate tasks are completed.
	- Get transactions API endpoint completed
	- Database created
	- Initial support for token price
- Work in progress for StorjScan API
	- Token price history
	- Transactions API endpoint
	- Wallet generation
- Next steps
	- Satellite side usage of StorjScan
	- Get QA satellite to run Storj test token payments

**Comment by shaupt131** [comment]
## Week 11 update:

- Continued making progress on satellite side 

**Nearing completion:**
- Ability to create and save Storjscan as payment type
- Collect and store Storj token price history at intervals
- Endpoint to generate new deposit address
- Add block header cache with search

**Next tasks:**
- Get lifetime total deposits in USD
- CLI to generate HD wallets
- Get QA satellite to run Storj test token payments

**Comment by shaupt131** [comment]
## Week 13 update:

- Continued satellite side work

**Completed:** 

- Collect and store Storj token price history at intervals

**Nearing completion:**

- Endpoint to generate new deposit address
- Add block header cache with search
- Ability to create and save Storjscan as payment type
- CLI to generate HD wallets

**Work in progress:**

- Get lifetime total deposits in USD

**Next Tasks:**

- Get QA satellite to run Storj test token payments

**Comment by shaupt131** [comment]
Week 15 update:

- Continued satellite side work

**Completed:**

- Add block header cache with search
- Get lifetime total deposits in USD
- Design Document Overview
- Endpoint to generate new deposit address

**Work in Progress:**

- Ability to create and save Storjscan as payment type
- CLI to generate HD wallets
- Design Document Details
- Periodically request payments from storjscan on satellite side 
- Create API endpoint stub for satellite UI
- Add StorjScan to StorjSim in docker-compose

**Next Tasks:**

- Figure out accounting with stripe

**Comment by iglesiasbrandon** [comment]
marking this item as completed because we have deployed this functionality into production
