### ISSUE TITLE
CI/CD of Satellite UI: Console team staging environments

### ISSUE THREAD

**Issue by stoweandi** [storj/roadmap#52]
### Goal
We want to be able to deploy frontend changes without being tied to backend satellite deployment process. This will allow us to move faster and more easily test new features. Today we can't get feedback until a change is merged -- after this milestone is complete the feedback cycle will be much quicker and we can get more iterations in with feedback from non-devs.

### In scope

- Separate the front end from backend (so that it can be deployed separately)
- Staging environments setup for Console team to use as needed

<img src="https://user-images.githubusercontent.com/7063002/222234192-abc4e665-2a32-4889-9386-cc1e9511acfd.png" width="50%">

### Out of scope
- CI/CD for backend satellite deployments

### Links

- CI/CD of Satellite Phase 1 Milestone: https://github.com/storj/storj/milestone/33

**Comment by NiaStorj** [comment]
Frontend CI/CD Satellite Code Changes Milestone: https://github.com/storj/storj/milestone/33
Frontend CI/CD build and deployment Milestone: https://github.com/storj/storj/milestone/34
ROM: 5 sprints

**Comment by iglesiasbrandon** [comment]
Moving the estimated completion sprint to 11, During sprint 10 we had some other tasks such as the custom pricing that ended up taking more of the team's resources to complete.

**Comment by ferristocrat** [comment]
See https://github.com/storj/nightly#how-to-use-an-environment for details on how to setup staging environment

**Comment by NiaStorj** [comment]
All tickets are merged. Just have not been deployed. moving to sprint 12 for that reason

**Comment by iglesiasbrandon** [comment]
We will move this out one more sprint because unfortunately, the final ticket for this roadmap item did not make the release cut for the deployment. The good news is the work for this roadmap item has been completed!

**Comment by iglesiasbrandon** [comment]
Update this roadmap item with the correct estimated completion sprint and milestone if applicable. @NiaStorj @ferristocrat
