### ISSUE TITLE
All Projects Dashboard - improved UX for viewing and managing projects

### ISSUE THREAD

**Issue by stoweandi** [storj/roadmap#55]
### What is the problem/pain point?

There are a few pain points that we hope to address:

- Users don't have a way to see all their projects in a single view.
- User is always defaulted to their first project in the list and it's not always clear how to get to the project a user wants to access when they log in. 
- People need to select a project first when logging in, to enter the correct project level passphrase. If people don't want to view project or their data, but only there for billing or account info, they can do that with the new projects dashboard. 

### What is the impact?

Confusion around the project level passphrase. Inability to get to billing without being prompted for a passphrase.

### Why now?

We switched the passphrase flow so it asks for a passphrase when opening a project.

### Links:
Milestone: https://github.com/storj/storj/milestone/1
Figma: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=14389%3A131874

**Comment by NiaStorj** [comment]
@littleskunk is the QA team able to write a test plan for this?

**Comment by iglesiasbrandon** [comment]
@ferristocrat @boshevski Please discuss this item and update the description.

**Comment by NiaStorj** [comment]
need to know when ix systems is ready to turn on their flag and then will have an idea of when this can be deployed. when ready we will need to turn on feature by default. 

we need to change this default to true to enable all projects dashboard next release https://github.com/storj/storj/blob/73898e0d86aef1a3d44de88d7e4c18fead5ee5ea/satellite/console/consoleweb/server.go#L94
[server.go](https://github.com/storj/storj/blob/73898e0d86aef1a3d44de88d7e4c18fead5ee5ea/satellite/console/consoleweb/server.go)
    AllProjectsDashboard            bool       `help:"indicates if all projects dashboard should be used" default:"false"`
<https://github.com/[storj/storj](https://github.com/storj/storj)|storj/storj>storj/storj | Added by [GitHub](https://storj.slack.com/services/B01UEU60A83)
[10:27](https://storj.slack.com/archives/D02UKQU5XCK/p1683221259114749)
ticket AC: change default to true, and notify config-changes and [#team-qa](https://storj.slack.com/archives/CBSEX8R1P)

**Comment by iglesiasbrandon** [comment]
QA has conducted their tests, and everything is looking good; this is on track to be deployed. @ferristocrat is going to speak to the team about A/B testing this somehow.

**Comment by NiaStorj** [comment]
pushed to sprint 16 due to tome wanting to see a table view and a couple bugs before deployment.

**Comment by iglesiasbrandon** [comment]
This item is completed and just waiting for QA/deployment on the 26th

**Comment by iglesiasbrandon** [comment]
The all project's dashboard has been completed and deployed to production. 

![Image](https://github.com/storj/roadmap/assets/5313116/df15e005-ab2a-4182-84ee-ad9d92d0be68)
