### ISSUE TITLE
Account Management API

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#6]
### Summary: 
We want to give users the ability to do things and stuff on their accounts programmatically. For example, create projects, add users, get billing data, and get data about their projects usage. The Satellite uses the Console API which is authenticated via a cookie that is inserted when a customer logs in. Although this approach is sufficient for using the Satellite GUI, it is suboptimal for a developer who wishes to programmatically perform operations on resources relating to his account. Therefore, both cookie-based authentication and API-key authentication must be supported in the new API.

### Pain Point:
 Users must log into the satellite GUI in order to do things such as create projects, update billing information and get data. These types of items are not available for users to update or get programmatically via API endpoints. 

### Intended Outcome:
Users will have the ability to do everything they can do in the satellite GUI programmatically via API endpoints. 

### How will it work?
Please see blueprint: https://review.dev.storj.io/c/storj/storj/+/6341

### Links:
Blueprint: https://review.dev.storj.io/c/storj/storj/+/6341
Milestone: https://github.com/storj/storj/milestone/4

**Comment by NiaStorj** [comment]
**### Week 23 Update:** 

Done.  MVP completed
