### ISSUE TITLE
Project Member Invite UX Revamp

### ISSUE THREAD

**Issue by ferristocrat** [storj/roadmap#65]
#### What is the problem/pain point?
Currently, the user experience for both managing project members as well as identifying projects that you are a member of (rather than an owner) is not very great. Furthermore, if you invite someone who doesn't already have an account registered on the Satellite, nothing will happen.

#### Who is impacted?
 - Customers who add project members
 - Customers who are added as project members
 - Customers trying to invite members who don't already have an account

#### What is the impact?
From the perspective of the project owner, it is impossible to tell if a project member has actually accepted a project invite, and it's also impossible to tell if the member even has a Storj account. Furthermore, if you are a project owner and member, it is difficult to determine which projects you are a member vs an owner.

#### Why now?
We have an MVP for managing project collaborators, but want to improve some things.

#### Acceptance Criteria
- Miscellaneous UI updates and functionality
  - https://github.com/storj/storj/issues/5742 
- The "Team" list contains a new column with the users "Role" which can be one of the following: Owner, Member, Invited
  - https://github.com/storj/storj/issues/5743
- Updated Project Invite UI
  - https://github.com/storj/storj/issues/5744
- A project owner can delete 1 or many project members at a time (existing functionality but updated designs)
  - https://github.com/storj/storj/issues/5751
- A project owner can resend an invite  for 1 or many project members at a time
  - https://github.com/storj/storj/issues/5752
- A user should be able to accept a project invite (existing functionality but updated designs):
  - If they are an existing user on the Satellite, they should be brought to the login page with the region and email pre-selected/filled
    - https://github.com/storj/storj/issues/5741
  - If they are NOT an existing user on the Satellite, they should be brought to the sign up page with the region pre-selected
    - https://github.com/storj/storj/issues/5353

#### Success Metrics
Success will be measured by:
 - Number of accounts with project members
 - Storage/Egress from accounts with project members

#### Figma Link
 - https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=8504-18815&t=FegXHb2ffcqMEeKr-0

#### Milestone(s)

- https://github.com/storj/storj/milestone/40

#### Blueprint
https://docs.google.com/document/d/1fYmCBsdzrgUlexPhOZFha9bY-gWUQb3LlEhXCpO-JO0/edit#heading=h.d50goufvvmo0

**Comment by iglesiasbrandon** [comment]
All of the tickets for this roadmap item have been completed! The only reason we are moving it back to Sprint 18 is because it did not make the cutoff date and it's not worth the effort to do a point release on July 3rd.

**Comment by NiaStorj** [comment]
Will be keeping project member invite in sprint 18 for now.  Depends on if the bug fixes are completed in time before the release. Jens mentioned that he's willing to cherry pick and push production deployment to next Tuesday.  

List of bugs that need to be fixed for deployment according to Jens:

- Remove member from the list
- Spam mails

**Comment by iglesiasbrandon** [comment]
this has been deployed! we are going to close this roadmap item!
