### ISSUE TITLE
Transistion to Free Trial

### ISSUE THREAD

**Issue by ferristocrat** [storj/roadmap#68]
## Description 
More Details can be found here: https://forum.storj.io/t/discontinuation-of-the-storj-free-tier/25332/81

## What’s Changing?

Storj is discontinuing the “[Free](https://docs.storj.io/dcs/pricing) Tier,” which historically was offered to allow users to try Storj. Current users of the Free Tier have from now until March 31 to upgrade to a Pro Account to continue using Storj. For users who already have a Pro Account, they will no longer receive the Free Tier coupon. We are encouraging users who do not want to upgrade to a Pro Account to migrate any data off Storj before their accounts are frozen.

**Comment by ferristocrat** [comment]
Sprint 35 - handed off to QA

**Comment by iglesiasbrandon** [comment]
This has been completed as of April 1st.
