### ISSUE TITLE
Security Improvements

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#7]
### Summary: 
V3 is focused on security with end-to-end encryption and macaroon-based access control but there are still security improvements we could make for users on the Satellite GUI. 

### Pain Points:
Currently, we do not have any of the following items implemented: 
- Alert users if they use a username/password combo that is in a breached database.
- Email users whenever they have logged in from a previously unseen IP address.
- Email users when new access grants are created on projects they are the admin of. 
- Account recovery keys for users.

### Intended Outcome:
Implement the items listed above to improve user account security.

### Links: 
- Milestone: https://github.com/storj/storj/milestone/9
- Private milestone: https://github.com/storj/storj-private/milestone/1
- Security improvements Document: https://storjlabs.atlassian.net/wiki/spaces/ENG/pages/2232221701/Security+Requirements

**Comment by jtolio** [comment]
https://storjlabs.atlassian.net/wiki/spaces/ENG/pages/2232221701/Security+Requirements

**Comment by NiaStorj** [comment]
Week 17 Updates:

Current Status:

- Implementation of the new sessions table has started. this will allow us to fix most of the security tickets we have issues for. 

Next Steps:

- Finish integrations of new sessions into sat. app
- Begin fixes for session-related issues
