### ISSUE TITLE
Delete/ Server Side Copy Refactor

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/roadmap#73]
Blue Print: https://review.dev.storj.io/c/storj/storj/+/9979/2/docs/blueprints/fix-deletes-and-server-side-copy.md 

Prerequisite for https://github.com/storj/roadmap/issues/40

Milestone: https://github.com/storj/storj/milestone/44

**Comment by shaupt131** [comment]
All satellites have been switched to the new SSC methodology, and migrations are complete.  Removal of old code is in progress.

**Comment by iglesiasbrandon** [comment]
All of the functionality for this effort has been completed and deployed to production. the only remaining ticket is to clean up/ delete the old code but we can call this done!
