### ISSUE TITLE
zkSync Era support for Storj Customers

### ISSUE THREAD

**Issue by ferristocrat** [storj/roadmap#81]
### Context: 

We currently support L1 STORJ token payments for Storj DCS customers. We want to enable our customers to pay for their Storj DCS usage with STORJ on an L2. Since we have been utilizing zkSync for Storage Node operator payments for the last two years with no issues, we have also adopted zkSync Era for l2 payments from our customers. 

### Pain Point

Depending on the transaction fees for L1 ETH transfers, depositing small amounts of STORJ tokens into your Storj DCS account can sometimes be too expensive. For example, if you want to deposit $10 USD worth of STORJ, but the transaction fee at that time on L1 is $5 USD, it may not be worthwhile. 

### Dependencies

- Dependent on https://github.com/storj/roadmap/issues/63 which adds zkSync Era support in StorjScan

### Acceptance Criteria: 

- We have added support for zkSync Era for accepting STORJ token in the Satellite UI
- We have added support for zkSync Era into https://github.com/storj/storjscan

### Designs
- Figma designs TBD

**Comment by mobyvb** [comment]
for now I would be comfortable with a ROM of 2-3 sprints. But it could be more complex than I'm thinking, and we should reassess once there are designs available

**Comment by mobyvb** [comment]
for now I would be comfortable with a ROM of 2-3 sprints. But it could be more complex than I'm thinking, and we should reassess once there are designs available

**Comment by ferristocrat** [comment]
Sprint 35 - to be deployed to QA and tested

Need to document UI changes (@ferristocrat ):
- We need to address the banner that claims we don't support zkSync payments
- We need to make sure the "view" button on payment history tab routes to the correct block explorer.

**Comment by iglesiasbrandon** [comment]
This roadmap issue has been completed!
