### ISSUE TITLE
Add Carbon Savings to Invoices

### ISSUE THREAD

**Issue by ferristocrat** [storj/roadmap#86]
### What is the problem/pain point?
While Storj's decentralized storage model inherently offers better sustainability compared to traditional centralized models, this advantage is not currently showcased to customers. In an era where environmental consciousness is paramount, highlighting our carbon savings can be a significant differentiator and value proposition.

### Who is impacted?
- Customers who prioritize environmental sustainability and need/want to know the carbon impact of their object storage use.
- Potential customers comparing Storj with competitors, looking for environmentally responsible solutions.

### What is the impact?
1. By clearly presenting the carbon footprint and comparative savings on invoices, Storj can effectively communicate its sustainability advantage, reinforcing its position as a more environmentally-friendly choice over traditional storage providers.
2. Customers equipped with this information can make data-driven decisions, potentially influencing their continued use of Storj and promoting it within their networks.
3. The transparency and emphasis on sustainability can enhance Storj's brand reputation, attracting businesses and sectors that prioritize environmental responsibility.
4. As sustainability becomes a key decision factor for many businesses, Storj's clear communication of its advantages can lead to increased customer acquisition and retention.

### Why now?
1. Competitors like Wasabi are already offering insights into carbon savings, but Storj has a unique advantage due to its decentralized model.
2. The global emphasis on sustainability is growing, and businesses that showcase their commitment stand out.
3. Leveraging our sustainability advantage can drive customer loyalty and attract new, environmentally-conscious users.

### User Story
As a Storj customer, I want to see both the carbon footprint of my cloud storage usage and the carbon savings achieved by using Storj compared to traditional providers on my invoice. This information will empower me to make informed business decisions and effectively communicate the sustainability advantages of my operations to stakeholders.

### Acceptance Criteria
1. Each invoice should clearly display the carbon footprint of the customer's cloud storage usage for the billing period.
2. Alongside the carbon footprint, the invoice should also showcase the carbon savings achieved by using Storj as compared to traditional storage providers.
3. The calculation methodology for both the carbon footprint and the comparative savings should be transparent, with references or links to sources or studies validating the method.
5. An option for customers to delve deeper into Storj's sustainability efforts, the carbon footprint calculation, and how the comparative savings are determined.

### Success Metrics
1. Positive feedback from customers regarding the clarity and usefulness of the carbon footprint and comparative savings information.
1. An uptick in mentions of Storj's sustainability features in customer testimonials, case studies, or public forums.
1. Demonstrable increase in customer retention or acquisition, particularly among businesses or sectors that prioritize sustainability.
1. Enhanced brand perception, with Storj being recognized as a leader in sustainable cloud storage solutions in industry reports, reviews, or surveys.

---

**References**:
- [Wasabi Carbon Calculator](https://wasabi.com/sustainability/)
- Storj formula: https://github.com/storj/experiments/blob/main/carbon-assessment/green.go

**Comment by iglesiasbrandon** [comment]
Work on this has began: https://review.dev.storj.io/c/storj/storj/+/12352

**Comment by iglesiasbrandon** [comment]
closing this issue, the work had been deployed to production.
