### ISSUE TITLE
Enhancing Global Consistency: Better Edge Performance in South America and Asia

### ISSUE THREAD

**Issue by ferristocrat** [storj/roadmap#90]
### Background
**What is the problem/pain point?**

Customers in South America and Asia (including Oceana) are currently experiencing higher latency and less reliable access compared to other regions, leading to inconsistent global performance.

**Who is impacted?**

Primarily customers in South America and Asia (including Oceana), and secondarily, any global enterprise that requires consistent performance across all regions for their operations.

**What is the impact?**

The inconsistency in service performance can lead to a fragmented user experience, with customers in some regions enjoying fast and reliable access, while others face delays and interruptions.

**Why now?**

Addressing this performance inconsistency is crucial for maintaining our reputation as a reliable global service provider. Ensuring uniform performance across all regions is a commitment to our customers' success and is essential for fostering trust and loyalty, especially as we serve customers that have a global presence.

### Requirements
**User Story**

As a customer in South America or Asia (including Oceana), I want to access and retrieve my data quickly and reliably, so I can have a consistent experience with the service, comparable to users in other regions.

**Acceptance Criteria**

1. Successful deployment of edge services in targeted areas of South America and Asia (serving Oceana as well).
2. Measurable reduction in latency for users in these regions, bringing their experience in line with global standards.
3. Uniform and reliable access to services across all regions.

**Success Metrics**

1. Global consistency in service performance metrics, with minimal variance between regions.
2. Improved customer satisfaction scores and positive feedback regarding consistency and reliability from customers with use in South America, Asia and Oceana (Australia in particular).
3. Retention and growth in customer base across all regions, driven by a universally positive user experience.

**Milestone(s)**
- https://github.com/storj/infra/milestone/33

### Productboard Link
 - https://storj.productboard.com/entity-detail/features/24295965

**Comment by amwolff** [comment]
Completed. I will defer to you @ferristocrat to close it, though.
