### ISSUE TITLE
Enhanced User Onboarding

### ISSUE THREAD

**Issue by ferristocrat** [storj/roadmap#92]
### Background
**What is the problem/pain point?**
The current Storj sign-up process is cumbersome, requiring extensive user information upfront, which creates a high barrier to entry and results in significant user drop-off. Post sign-up, there is a noticeable decline in user engagement, particularly after the bucket creation step. The journey to realizing value is currently too lengthy, involving several steps: signing up, optionally setting up a credit card, creating a project, creating the first bucket, and finally creating S3 credentials for programmatic interaction or proceeding without them to use the UI for object storage operations. This roadmap item aims to streamline the process, particularly focusing on users who utilize the S3 credentials for managing their storage needs, to ensure a seamless transition to the value-providing aspects of the platform.

**Who is impacted?**
- New users during the initial sign-up and setup phase.
- Customer support teams dealing with issues arising from the current onboarding complexities.

**What is the impact?**
By reducing friction during sign-up and simplifying the steps to start using Storj, we anticipate a decrease in user drop-off rates and an increase in use and satisfaction. This should lead to a more robust user base and a higher rate of conversion from sign-up to active use.

**Why now?**
Optimizing the onboarding process is critical to reducing initial user churn and capitalizing on the user's intent to engage with the platform. Acting now will help us to retain more users in the long run and enhance the overall adoption of Storj.

### Requirements
**User Story**
As a new Storj user, I want a clear and guided onboarding process, so I can efficiently set up my account and start using the Storj with ease.

***Acceptance Criteria (Draft/TBD)**
_These criteria are initial drafts and will be refined based on the final Vuetify design prototype._

1. The onboarding interface should be a faithful implementation of the Vuetify mockups here: https://storj.github.io/vuetify-storj

**Screenshots from above design**
| Description | Screenshot |
| --- | --- |
| Sign up | ![Image](https://github.com/storj/roadmap/assets/7063002/18fe4e7a-5460-49f4-bc02-adeb0bf5aaf9) |
| Code from email verification | ![Image](https://github.com/storj/roadmap/assets/7063002/2dbca5c8-4b9b-4aba-9a32-51a394f2bf61) |
| Choose account type | ![Image](https://github.com/storj/roadmap/assets/7063002/8faaaa5b-903b-4406-b8e7-57c854f15994) |
| Personal info collection | ![Image](https://github.com/storj/roadmap/assets/7063002/b12b46f5-9180-45e9-8710-ad71eb96e19e) |
| Business info collection | ![Image](https://github.com/storj/roadmap/assets/7063002/0277e5e2-b6a1-48b8-838a-a9cbd9452d6f) |
| Final Confirmation | ![Image](https://github.com/storj/roadmap/assets/7063002/2e1149d3-799a-4224-8df1-5d4ce93b7955) |
| First Actions Steps | ![Image](https://github.com/storj/roadmap/assets/7063002/dc2fa9a5-0484-4379-b73f-93bb8ca4d03c) |

### Success Metrics
1. A reduction in the average time it takes for users to complete the onboarding process.
2. An increase in the conversion rate of new sign-ups post-launch of the new design.
3. Positive feedback from users on the onboarding experience.
4. A decrease in customer support tickets related to account setup.

**Comment by iglesiasbrandon** [comment]
Moving this item to closed because it's already been completed.
