### ISSUE TITLE
Region Tag Added to Buckets in Satellite UI (Storj Select)

### ISSUE THREAD

**Issue by ferristocrat** [storj/roadmap#95]
#### What is the problem/pain point?
Currently, users cannot easily identify the region (Global or Select) of buckets in the Satellite UI. Providing visible region tags on each bucket will enhance user understanding and efficiency in managing their data storage.

#### Who is impacted?
- Users managing multiple buckets with varying regional configurations.
- Users who need to quickly identify the type of bucket.

#### What is the impact?
- Improved clarity and ease of use for users managing buckets in the Satellite UI.
- Enhanced user experience by providing immediate visibility of the bucket's region.

#### Why now?
Adding this feature gives customers peace of mind that the bucket is configured correctly, given that the "select" designation is currently a "contact us to enable" feature. Furthermore, it makes it easier to quickly identify a bucket as "US Select" without needing to use S3 APIs.

#### User Story
As a Storj user, I want to see clearly labeled region tags on each bucket within the Satellite UI so that I can easily understand and manage my data storage configurations.

#### Acceptance Criteria
1. Region tags should be visibly displayed next to each bucket's name on the bucket list page.
2. Tags must be clear, concise, and easily distinguishable between `Global` and `US Select` options.
3. Documentation should be updated, explaining the significance of these tags and their role in bucket management.

#### Design
- See https://storj.github.io/vuetify-storj for the latest source of truth

| Description | Screenshot |
| --- | --- |
| Bucket list | ![image](https://github.com/storj/roadmap/assets/7063002/df051559-b3d5-4b0a-83e4-7e3a79e8be5e) |
| Bucket browse page | ![image](https://github.com/storj/roadmap/assets/7063002/4f9843b8-b8f9-4e5f-9bdb-9c529b100710) |

#### Success Metrics
- Positive feedback from users on the utility and clarity of the region tags.
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6685
```

**Comment by iglesiasbrandon** [comment]
relevant ticket https://github.com/storj/storj/issues/6685

**Comment by ferristocrat** [comment]
Sprint 35 - complete but not in production yet

**Comment by iglesiasbrandon** [comment]
This roadmap item has been completed!
