### ISSUE TITLE
Object Versioning: Add Versioning Tag in Web Console

### ISSUE THREAD

**Issue by ferristocrat** [storj/roadmap#96]
#### What is the problem/pain point?
Users currently lack a straightforward way to identify if buckets are versioned from the Storj web console. A visible versioning tag will allow users to easily view the versioning configuration of their buckets.

#### Who is impacted?
- Users who utilize object versioning and require a quick reference to the versioning configuration of their buckets.

#### What is the impact?
- Enhanced user experience by allowing easy identification of which buckets have versioning enabled.

#### Why now?
With the release of object versioning, we want to minimize friction and successful adoption as possible. Simple readonly information about a buckets versioning configuration is the low hanging fruit in the web console to achieve this.

#### User Story
As a Storj user, I want to see a visible tag or indicator next to buckets that have versioning enabled, allowing me to quickly discern their versioning status.

#### Acceptance Criteria
1. Each bucket with versioning enabled should have a clearly visible tag or icon indicating its versioned status.
2. Documentation should be updated, explaining the significance of these tags and their role in bucket management.

#### Design
- See https://storj.github.io/vuetify-storj for the latest source of truth

| Description | Screenshot |
| --- | --- |
| Bucket list | ![image](https://github.com/storj/roadmap/assets/7063002/27a996ad-f26a-479d-b4cf-fd31b279d5e3) |

#### Out of Scope
- Full management of object versions in the web console including:
  - Viewing versions of objects other than the current version from the web console
  - Deleting or reverting to older versions of an object from the web console

#### Success Metrics
- Positive feedback from users on the utility and clarity of the versioning tag.
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6683
```

**Comment by iglesiasbrandon** [comment]
this work has been completed! going to close this issue.
