### ISSUE TITLE
S3 Object lock: Governance Mode and Legal Hold

### ISSUE THREAD

**Issue by ferristocrat** [storj/roadmap#98]
### Summary
Our current implementation of S3 Compatible Object Lock only accounts for Compliance Mode. This roadmap item is meant to cover the remaining functionality to complete full Object Lock compatibility.

#### New S3 Actions Supported

| S3 Action | Description | Notes | Associated GitHub Issues | 
|---|---|---|---|
| PutObjectLockConfiguration | Enables Object Lock configuration on a bucket. | **ObjectLockEnabled**: Indicates if Object Lock is enabled on the bucket. <br><br>**Rule**: Specifies the Object Lock rule (mode and period) for the bucket. The period can be either `Days` or `Years`. | Design: https://github.com/storj/edge/issues/471<br><br>Satellite: https://github.com/storj/edge/issues/500<br><br>Schema changes: https://github.com/storj/edge/issues/502<br><br>Gateway: https://github.com/storj/edge/issues/501|
| GetObjectLegalHold | Retrieves the Legal Hold status of an object. | - | Satellite: https://github.com/storj/edge/issues/481<br><br>Gateway: https://github.com/storj/edge/issues/483 |
| PutObjectLegalHold | Applies a Legal Hold to the specified object. | - | Satellite: https://github.com/storj/edge/issues/482<br><br>Gateway: https://github.com/storj/edge/issues/484 |

#### Existing operations to update

| S3 Action | Description | Updates | Associated GitHub Issues | 
|---|---|---|---|
| GetObjectLockConfiguration | Retrieves the Object Lock configuration of a bucket. | Returns any Rule applied via PutObjectLockConfiguration. | Satellite: https://github.com/storj/edge/issues/471<br><br>Gateway: https://github.com/storj/edge/issues/485 |
| DeleteBucket | Deletes an empty bucket. | Ensures buckets with active object locks cannot be deleted. | Satellite: https://github.com/storj/edge/issues/474<br><br>Gateway: https://github.com/storj/edge/issues/486 |
| PutObject | Adds an object to a bucket. | Supports request params: `x-amz-object-lock-mode` (including GOVERNANCE mode), `x-amz-object-lock-legal-hold` | Satellite: https://github.com/storj/edge/issues/469<br><br>Gateway:  https://github.com/storj/edge/issues/487 |
| GetObjectRetention | Retrieves the retention settings of an object. | Returns GOVERNANCE mode for objects locked with Governance Mode in addition to what's already implemented for COMPLIANCE mode. | Satellite: https://github.com/storj/edge/issues/475<br><br>Gateway: https://github.com/storj/edge/issues/488  |
| PutObjectRetention | Applies retention settings to an object. | Supports request params: `x-amz-bypass-governance-retention`. Now accepts GOVERNANCE Mode. | Satellite: https://github.com/storj/edge/issues/476<br><br>Gateway: https://github.com/storj/edge/issues/489 |
| HeadObject | Retrieves metadata from an object. | Returns object lock information in the metadata response: `x-amz-object-lock-mode`, `x-amz-object-lock-retain-until-date`, `x-amz-object-lock-legal-hold` | Satellite: https://github.com/storj/edge/issues/477<br><br>Gateway: https://github.com/storj/edge/issues/490 |
| GetObject | Retrieves an object. | Returns object lock information in the response headers: `x-amz-object-lock-mode`, `x-amz-object-lock-retain-until-date`, `x-amz-object-lock-legal-hold`. | Satellite: https://github.com/storj/edge/issues/478<br><br>Gateway: https://github.com/storj/edge/issues/491 |
| FinishMoveObject | Finalizes moving an object within the same bucket. | Ensures object lock settings (mode, retain-until-date, legal hold) are retained. | Satellite: https://github.com/storj/edge/issues/479<br><br>Gateway: https://github.com/storj/edge/issues/492 |
| CopyObject | Creates a copy of an object. | Ensures object lock settings (mode, retain-until-date, legal hold) are copied. Supports headers to override lock settings: `x-amz-copy-source-object-lock-mode`, `x-amz-copy-source-object-lock-retain-until-date`, `x-amz-copy-source-object-lock-legal-hold` | Satellite: https://github.com/storj/edge/issues/480<br><br>Gateway: https://github.com/storj/edge/issues/493 |
| DeleteObject | Deletes a specific version of an object. | Ensures objects in Compliance Mode or with Legal Hold cannot be deleted. Allows deletion of objects in Governance Mode with `x-amz-bypass-governance-retention` and s3:BypassGovernanceRetention permission. | Satellite: https://github.com/storj/edge/issues/468<br><br>Gateway: https://github.com/storj/edge/issues/494 |

#### New permissions/access to consider
| S3 Permission | Description | Notes |
|---|---|---|
| s3:BypassGovernanceRetention | Grants permission to allow circumvention of governance-mode object retention settings | Notes on how this permission is utilized/how it works: [Object Lock considerations - Amazon Simple Storage Service](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-managing.html#object-lock-managing-bypass) |
| s3:PutBucketObjectLockConfiguration | Grants permission to put Object Lock configuration on a specific bucket. |  |
| s3:GetObjectLegalHold | Grants permission to get an object's current Legal Hold status |  |
| s3:PutObjectLegalHold | Grants permission to apply a Legal Hold configuration to the specified object |  |

**Comment by jtolio** [comment]
https://docs.google.com/document/d/1gQK7Obw2NHJNIbR2FasZVGN8G3cVWrOCuny6d9xp1IA/edit

**Comment by shaupt131** [comment]
Release to production on Oct-14-2024.  With this, all object lock features are now in production.
